### ISSUE TITLE
Shouldn’t a null sedenion 

### ISSUE THREAD

**Issue by psychoslave** [discretegames/hypercomplex#3]
As noted in the README sedenions and beyond have zero divisors.
```python
s0 = Sedenion() # (0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)
s1 = Sedenion.e(5) + Sedenion.e(10)
s1/s0 # ZeroDivisionError, when I would expect the divistion to yield a sedenion
```

So is it me who misunderstood "having zero divisor", or is it just something unsupported in this implementation?

**Comment by discretegames** [comment]
Hmm, this is a good question and may be a limitation of the implementation. In the code, division is done by first inverting then multiplying, so it gets to [this line](https://github.com/discretegames/hypercomplex/blob/main/hypercomplex/hypercomplex.py#L16) which tries to divide by a float 0 giving a ZeroDivisionError.

Though I don't have the math knowledge to fully answer. Do sedenions have unique zero divisors, i.e. does `s0/s1` gives a single answer, namely `s2 = Sedenion.e(6) + Sedenion.e(9)`? [A chart on wiki seems to say so](https://en.wikipedia.org/wiki/Sedenion#Quaternionic_subalgebras) but I may be reading it wrong.

If so, then there may be a way to fix the code. If not, then I'm really not sure how multiple results could be handled 😅

**Comment by discretegames** [comment]
With help from someone smarter than me I've realized that of course, there are lots of `s2 = s0/s1` that could work, namely any scalar multiple of `Sedenion.e(6) + Sedenion.e(9)` like `2 * (Sedenion.e(6) + Sedenion.e(9))`. The code will give `0` for `s0/s1` which seems like a reasonable choice.

**More importantly** I've realized the original question was about `s1/s0`, not `s0/s1`. Sorry for the mixup there. Having [zero divisors](https://en.wikipedia.org/wiki/Zero_divisor) means you can have two non-zero sedenions `s1` and `s2` where `s1*s2 = 0`  which implies `s2 = 0/s1`, but doesn't mean you can divide by 0. So things are working as intended.
