### ISSUE TITLE
References

### ISSUE THREAD

**Issue by VascoSch92** [discretegames/hypercomplex#4]
Hey,

congrats for the package. It is really nice :-)

I wanted to know if you have references for `Pathion`, `Chingon`, `Routon`, `Voudon`

I searched in internet but I found nothing.

Thanks :-)

**Comment by discretegames** [comment]
Thanks. Yeah, the source for the names is explained in the readme right before the "Thorough Usage Examples".

**Comment by VascoSch92** [comment]
Thank you for your answer. 

It is really interesting. 

Are you still maintaining this package or not ?
